"""Curated Indian destination database — multi-category.

Supersedes agent.hill_stations (which remains as a deprecated alias).
All 30 hill-station entries are migrated here with categories: the
hill-only entries keep ["hill_station"], others gain their extra
categories. Sources cross-referenced: India Tourism, state tourism
boards, Wikipedia.
"""

# (name, state, lat, lng, elevation_m, categories)
DESTINATIONS = [
    # ---------------- Tamil Nadu ----------------
    {"name": "Udhagamandalam (Ooty)", "state": "Tamil Nadu", "lat": 11.4064, "lng": 76.6932, "elevation_m": 2240, "categories": ["hill_station", "lake", "heritage"]},
    {"name": "Coonoor", "state": "Tamil Nadu", "lat": 11.3530, "lng": 76.7950, "elevation_m": 1850, "categories": ["hill_station", "tea"]},
    {"name": "Kotagiri", "state": "Tamil Nadu", "lat": 11.4200, "lng": 76.8600, "elevation_m": 1793, "categories": ["hill_station", "trekking"]},
    {"name": "Kodaikanal", "state": "Tamil Nadu", "lat": 10.2381, "lng": 77.4892, "elevation_m": 2133, "categories": ["hill_station", "lake", "trekking"]},
    {"name": "Yercaud", "state": "Tamil Nadu", "lat": 11.7753, "lng": 78.2097, "elevation_m": 1515, "categories": ["hill_station", "coffee"]},
    {"name": "Yelagiri", "state": "Tamil Nadu", "lat": 12.5810, "lng": 78.6395, "elevation_m": 1410, "categories": ["hill_station", "adventure"]},
    {"name": "Kolli Hills", "state": "Tamil Nadu", "lat": 11.2500, "lng": 78.3333, "elevation_m": 1300, "categories": ["hill_station", "waterfall", "trekking"]},
    {"name": "Valparai", "state": "Tamil Nadu", "lat": 10.3230, "lng": 76.9518, "elevation_m": 1193, "categories": ["hill_station", "tea", "wildlife"]},
    {"name": "Sirumalai", "state": "Tamil Nadu", "lat": 10.2830, "lng": 77.9500, "elevation_m": 1600, "categories": ["hill_station", "offbeat"]},
    {"name": "Gudalur", "state": "Tamil Nadu", "lat": 11.4976, "lng": 76.4935, "elevation_m": 1072, "categories": ["hill_station", "wildlife"]},
    {"name": "Manjolai", "state": "Tamil Nadu", "lat": 8.6333, "lng": 77.4167, "elevation_m": 1200, "categories": ["hill_station", "offbeat", "trekking"]},
    {"name": "Courtallam", "state": "Tamil Nadu", "lat": 8.9400, "lng": 77.2760, "elevation_m": 160, "categories": ["waterfall", "pilgrimage"]},
    {"name": "Kanyakumari", "state": "Tamil Nadu", "lat": 8.0883, "lng": 77.5385, "elevation_m": 30, "categories": ["beach", "temple", "heritage"]},
    {"name": "Rameswaram", "state": "Tamil Nadu", "lat": 9.2876, "lng": 79.3129, "elevation_m": 10, "categories": ["temple", "pilgrimage", "beach"]},
    {"name": "Madurai", "state": "Tamil Nadu", "lat": 9.9252, "lng": 78.1198, "elevation_m": 101, "categories": ["temple", "heritage"]},
    {"name": "Mahabalipuram", "state": "Tamil Nadu", "lat": 12.6208, "lng": 80.1945, "elevation_m": 12, "categories": ["heritage", "beach"]},
    {"name": "Pondicherry", "state": "Puducherry", "lat": 11.9416, "lng": 79.8083, "elevation_m": 3, "categories": ["beach", "heritage", "offbeat"]},
    {"name": "Chidambaram", "state": "Tamil Nadu", "lat": 11.3992, "lng": 79.6912, "elevation_m": 3, "categories": ["temple", "pilgrimage"]},
    {"name": "Kumbakonam", "state": "Tamil Nadu", "lat": 10.9601, "lng": 79.3845, "elevation_m": 26, "categories": ["temple", "pilgrimage", "heritage"]},
    {"name": "Hogenakkal", "state": "Tamil Nadu", "lat": 12.1167, "lng": 77.7833, "elevation_m": 400, "categories": ["waterfall", "offbeat"]},
    # ---------------- Kerala ----------------
    {"name": "Munnar", "state": "Kerala", "lat": 10.0889, "lng": 77.0595, "elevation_m": 1600, "categories": ["hill_station", "tea", "trekking"]},
    {"name": "Thekkady", "state": "Kerala", "lat": 9.6000, "lng": 77.1600, "elevation_m": 900, "categories": ["wildlife", "hill_station", "spice"]},
    {"name": "Vagamon", "state": "Kerala", "lat": 9.6833, "lng": 76.9000, "elevation_m": 1100, "categories": ["hill_station", "adventure", "offbeat"]},
    {"name": "Ponmudi", "state": "Kerala", "lat": 8.7600, "lng": 77.1167, "elevation_m": 1100, "categories": ["hill_station", "trekking"]},
    {"name": "Peermade", "state": "Kerala", "lat": 9.5667, "lng": 76.9833, "elevation_m": 915, "categories": ["hill_station", "plantation"]},
    {"name": "Idukki", "state": "Kerala", "lat": 9.8500, "lng": 76.9667, "elevation_m": 750, "categories": ["hill_station", "dam", "wildlife"]},
    {"name": "Wayanad", "state": "Kerala", "lat": 11.6854, "lng": 76.1320, "elevation_m": 975, "categories": ["hill_station", "wildlife", "cave", "trekking"]},
    {"name": "Vythiri", "state": "Kerala", "lat": 11.5333, "lng": 76.0333, "elevation_m": 900, "categories": ["hill_station", "offbeat"]},
    {"name": "Alleppey", "state": "Kerala", "lat": 9.4981, "lng": 76.3388, "elevation_m": 1, "categories": ["backwater", "beach"]},
    {"name": "Kumarakom", "state": "Kerala", "lat": 9.6170, "lng": 76.4280, "elevation_m": 1, "categories": ["backwater", "birding"]},
    {"name": "Kovalam", "state": "Kerala", "lat": 8.4004, "lng": 76.9784, "elevation_m": 5, "categories": ["beach"]},
    {"name": "Varkala", "state": "Kerala", "lat": 8.7379, "lng": 76.7163, "elevation_m": 30, "categories": ["beach", "pilgrimage"]},
    {"name": "Kochi", "state": "Kerala", "lat": 9.9312, "lng": 76.2673, "elevation_m": 0, "categories": ["heritage", "backwater"]},
    {"name": "Athirappilly", "state": "Kerala", "lat": 10.2850, "lng": 76.5690, "elevation_m": 100, "categories": ["waterfall"]},
    {"name": "Guruvayur", "state": "Kerala", "lat": 10.5944, "lng": 76.0380, "elevation_m": 12, "categories": ["temple", "pilgrimage"]},
    # ---------------- Karnataka ----------------
    {"name": "Chikkamagaluru", "state": "Karnataka", "lat": 13.3161, "lng": 75.7720, "elevation_m": 1090, "categories": ["hill_station", "coffee", "trekking"]},
    {"name": "Kemmangundi", "state": "Karnataka", "lat": 13.5333, "lng": 75.7500, "elevation_m": 1434, "categories": ["hill_station", "waterfall"]},
    {"name": "Kudremukh", "state": "Karnataka", "lat": 13.2500, "lng": 75.2500, "elevation_m": 1894, "categories": ["hill_station", "trekking", "wildlife"]},
    {"name": "Madikeri (Coorg)", "state": "Karnataka", "lat": 12.4200, "lng": 75.7400, "elevation_m": 1150, "categories": ["hill_station", "coffee"]},
    {"name": "Mudigere", "state": "Karnataka", "lat": 13.1333, "lng": 75.6333, "elevation_m": 900, "categories": ["hill_station", "coffee", "offbeat"]},
    {"name": "Nandi Hills", "state": "Karnataka", "lat": 13.3702, "lng": 77.6835, "elevation_m": 1478, "categories": ["hill_station", "trekking"]},
    {"name": "BR Hills", "state": "Karnataka", "lat": 11.9167, "lng": 77.1167, "elevation_m": 1000, "categories": ["hill_station", "wildlife", "trekking"]},
    {"name": "Gokarna", "state": "Karnataka", "lat": 14.5500, "lng": 74.3230, "elevation_m": 10, "categories": ["beach", "temple", "offbeat"]},
    {"name": "Murudeshwar", "state": "Karnataka", "lat": 14.0940, "lng": 74.4880, "elevation_m": 5, "categories": ["beach", "temple"]},
    {"name": "Hampi", "state": "Karnataka", "lat": 15.3350, "lng": 76.4600, "elevation_m": 400, "categories": ["heritage", "offbeat", "trekking"]},
    {"name": "Coorg", "state": "Karnataka", "lat": 12.4200, "lng": 75.7400, "elevation_m": 1150, "categories": ["hill_station", "coffee", "trekking"]},
    {"name": "Sakleshpur", "state": "Karnataka", "lat": 12.9530, "lng": 75.7860, "elevation_m": 949, "categories": ["hill_station", "trekking", "offbeat"]},
    {"name": "Agumbe", "state": "Karnataka", "lat": 13.5030, "lng": 75.0900, "elevation_m": 826, "categories": ["waterfall", "offbeat", "trekking"]},
    {"name": "Jog Falls", "state": "Karnataka", "lat": 14.2290, "lng": 74.8120, "elevation_m": 488, "categories": ["waterfall"]},
    {"name": "Bandipur", "state": "Karnataka", "lat": 11.6650, "lng": 76.6280, "elevation_m": 1000, "categories": ["wildlife"]},
    {"name": "Nagarhole", "state": "Karnataka", "lat": 12.0167, "lng": 76.1500, "elevation_m": 900, "categories": ["wildlife"]},
    {"name": "Sravanabelagola", "state": "Karnataka", "lat": 12.8577, "lng": 76.4852, "elevation_m": 900, "categories": ["heritage", "pilgrimage"]},
    {"name": "Mysore", "state": "Karnataka", "lat": 12.2958, "lng": 76.6394, "elevation_m": 763, "categories": ["heritage", "palace"]},
    # ---------------- Andhra / Telangana ----------------
    {"name": "Horsley Hills", "state": "Andhra", "lat": 13.6579, "lng": 78.4078, "elevation_m": 1265, "categories": ["hill_station", "offbeat"]},
    {"name": "Araku Valley", "state": "Andhra", "lat": 18.3273, "lng": 82.8753, "elevation_m": 911, "categories": ["hill_station", "coffee", "cave"]},
    {"name": "Lambasingi", "state": "Andhra", "lat": 17.8100, "lng": 82.4833, "elevation_m": 1000, "categories": ["hill_station", "offbeat"]},
    {"name": "Tirupati", "state": "Andhra", "lat": 13.6288, "lng": 79.4192, "elevation_m": 153, "categories": ["temple", "pilgrimage"]},
    {"name": "Warangal", "state": "Telangana", "lat": 17.9689, "lng": 79.5941, "elevation_m": 302, "categories": ["heritage"]},
    {"name": "Papikondalu", "state": "Telangana", "lat": 17.3000, "lng": 81.1000, "elevation_m": 50, "categories": ["backwater", "offbeat"]},
    # ---------------- Maharashtra / Goa ----------------
    {"name": "Mahabaleshwar", "state": "Maharashtra", "lat": 17.9307, "lng": 73.6477, "elevation_m": 1353, "categories": ["hill_station", "strawberry"]},
    {"name": "Lonavala", "state": "Maharashtra", "lat": 18.7546, "lng": 73.4062, "elevation_m": 622, "categories": ["hill_station", "waterfall"]},
    {"name": "Matheran", "state": "Maharashtra", "lat": 18.9863, "lng": 73.2674, "elevation_m": 800, "categories": ["hill_station", "offbeat"]},
    {"name": "Panchgani", "state": "Maharashtra", "lat": 17.9229, "lng": 73.8139, "elevation_m": 1293, "categories": ["hill_station"]},
    {"name": "Goa", "state": "Goa", "lat": 15.2993, "lng": 74.1240, "elevation_m": 10, "categories": ["beach", "heritage"]},
    {"name": "Ajranta-Ellora", "state": "Maharashtra", "lat": 20.0170, "lng": 75.1780, "elevation_m": 600, "categories": ["cave", "heritage"]},
    # ---------------- North India ----------------
    {"name": "Shimla", "state": "Himachal Pradesh", "lat": 31.1048, "lng": 77.1734, "elevation_m": 2276, "categories": ["hill_station", "heritage"]},
    {"name": "Manali", "state": "Himachal Pradesh", "lat": 32.2432, "lng": 77.1892, "elevation_m": 2050, "categories": ["hill_station", "adventure", "trekking"]},
    {"name": "Dharamshala", "state": "Himachal Pradesh", "lat": 32.2190, "lng": 76.3234, "elevation_m": 1457, "categories": ["hill_station", "pilgrimage"]},
    {"name": "Kasol", "state": "Himachal Pradesh", "lat": 32.0050, "lng": 77.3160, "elevation_m": 1640, "categories": ["hill_station", "offbeat", "trekking"]},
    {"name": "Mussoorie", "state": "Uttarakhand", "lat": 30.4598, "lng": 78.0662, "elevation_m": 2005, "categories": ["hill_station"]},
    {"name": "Nainital", "state": "Uttarakhand", "lat": 29.3803, "lng": 79.4636, "elevation_m": 2084, "categories": ["hill_station", "lake"]},
    {"name": "Rishikesh", "state": "Uttarakhand", "lat": 30.0869, "lng": 78.2676, "elevation_m": 372, "categories": ["pilgrimage", "adventure", "temple"]},
    {"name": "Haridwar", "state": "Uttarakhand", "lat": 29.9457, "lng": 78.1642, "elevation_m": 314, "categories": ["pilgrimage", "temple"]},
    {"name": "Auli", "state": "Uttarakhand", "lat": 30.5300, "lng": 79.5700, "elevation_m": 2800, "categories": ["hill_station", "adventure", "trekking"]},
    {"name": "Jim Corbett", "state": "Uttarakhand", "lat": 29.5300, "lng": 78.7747, "elevation_m": 400, "categories": ["wildlife"]},
    {"name": "Jaipur", "state": "Rajasthan", "lat": 26.9124, "lng": 75.7873, "elevation_m": 431, "categories": ["heritage", "palace"]},
    {"name": "Udaipur", "state": "Rajasthan", "lat": 24.5854, "lng": 73.7125, "elevation_m": 598, "categories": ["heritage", "lake", "palace"]},
    {"name": "Jaisalmer", "state": "Rajasthan", "lat": 26.9157, "lng": 70.9083, "elevation_m": 225, "categories": ["desert", "heritage"]},
    {"name": "Pushkar", "state": "Rajasthan", "lat": 26.4870, "lng": 74.5510, "elevation_m": 510, "categories": ["pilgrimage", "temple"]},
    {"name": "Mount Abu", "state": "Rajasthan", "lat": 24.5925, "lng": 72.7156, "elevation_m": 1220, "categories": ["hill_station", "lake"]},
    {"name": "Agra", "state": "Uttar Pradesh", "lat": 27.1767, "lng": 78.0081, "elevation_m": 171, "categories": ["heritage"]},
    {"name": "Varanasi", "state": "Uttar Pradesh", "lat": 25.3176, "lng": 82.9739, "elevation_m": 81, "categories": ["pilgrimage", "temple", "heritage"]},
    {"name": "Mathura", "state": "Uttar Pradesh", "lat": 27.4924, "lng": 77.6737, "elevation_m": 174, "categories": ["pilgrimage", "temple"]},
    {"name": "Vrindavan", "state": "Uttar Pradesh", "lat": 27.5804, "lng": 77.6990, "elevation_m": 170, "categories": ["pilgrimage", "temple"]},
    {"name": "Amritsar", "state": "Punjab", "lat": 31.6340, "lng": 74.8723, "elevation_m": 234, "categories": ["pilgrimage", "heritage"]},
    {"name": "Rann of Kutch", "state": "Gujarat", "lat": 23.8500, "lng": 69.8000, "elevation_m": 15, "categories": ["desert", "offbeat"]},
    {"name": "Statue of Unity", "state": "Gujarat", "lat": 21.8379, "lng": 73.7191, "elevation_m": 100, "categories": ["heritage", "offbeat"]},
    # ---------------- East / Northeast ----------------
    {"name": "Darjeeling", "state": "West Bengal", "lat": 27.0410, "lng": 88.2663, "elevation_m": 2042, "categories": ["hill_station", "tea", "trekking"]},
    {"name": "Kalimpong", "state": "West Bengal", "lat": 27.0600, "lng": 88.4700, "elevation_m": 1250, "categories": ["hill_station", "offbeat"]},
    {"name": "Gangtok", "state": "Sikkim", "lat": 27.3389, "lng": 88.6065, "elevation_m": 1650, "categories": ["hill_station", "lake", "monastery"]},
    {"name": "Pelling", "state": "Sikkim", "lat": 27.2960, "lng": 88.2420, "elevation_m": 2150, "categories": ["hill_station", "monastery", "offbeat"]},
    {"name": "Shillong", "state": "Meghalaya", "lat": 25.5788, "lng": 91.8933, "elevation_m": 1496, "categories": ["hill_station", "waterfall"]},
    {"name": "Cherrapunji", "state": "Meghalaya", "lat": 25.3000, "lng": 91.7000, "elevation_m": 1484, "categories": ["waterfall", "cave", "offbeat"]},
    {"name": "Kaziranga", "state": "Assam", "lat": 26.5775, "lng": 93.1711, "elevation_m": 80, "categories": ["wildlife"]},
    {"name": "Tawang", "state": "Arunachal Pradesh", "lat": 27.5860, "lng": 91.8680, "elevation_m": 2669, "categories": ["hill_station", "monastery", "offbeat"]},
    {"name": "Puri", "state": "Odisha", "lat": 19.8135, "lng": 85.8312, "elevation_m": 3, "categories": ["beach", "temple", "pilgrimage"]},
    {"name": "Konark", "state": "Odisha", "lat": 19.8876, "lng": 86.0945, "elevation_m": 2, "categories": ["heritage", "beach"]},
]


# Aliases for LLM/NER category words -> canonical DB categories.
CATEGORY_ALIASES = {
    "hill": "hill_station",
    "hillstation": "hill_station",
    "mountain": "hill_station",
    "highland": "hill_station",
    "sea": "beach",
    "coast": "beach",
    "coastal": "beach",
    "shore": "beach",
    "wildlife_sanctuary": "wildlife",
    "safari": "wildlife",
    "national_park": "wildlife",
    "unesco": "heritage",
    "unesco": "heritage",
    "forts": "heritage",
    "palace": "palace",
    "temples": "temple",
    "pilgrim": "pilgrimage",
    "spiritual": "pilgrimage",
    "backwaters": "backwater",
    "houseboat": "backwater",
    "tea": "tea",
    "coffee": "coffee",
    "plantation": "tea",
    "spice": "spice",
    "waterfalls": "waterfall",
    "falls": "waterfall",
    "caves": "cave",
    "trek": "trekking",
    "treks": "trekking",
    "hiking": "trekking",
    "adventure_sports": "adventure",
    "rafting": "adventure",
    "paragliding": "adventure",
    "lakes": "lake",
    "lake": "lake",
    "desert": "desert",
    "dunes": "desert",
    "offbeat": "offbeat",
    "hidden": "offbeat",
    "quiet": "offbeat",
    "monasteries": "monastery",
    "monastery": "monastery",
    "birding": "birding",
    "birds": "birding",
    "dam": "dam",
    "dams": "dam",
}
